import type {
  AuditEvent,
  Certificate,
  Device,
  Job,
  RecoveredFile,
  SanitizationPlan,
} from "./types";

export const MOCK_DEVICES: Device[] = [
  {
    id: "dev-hdd-1",
    path: "/dev/sda",
    type: "HDD",
    model: "Seagate Barracuda 2TB",
    serial: "SG2T-88213",
    sizeBytes: "2000398934016",
    mounted: false,
    isSystemDisk: false,
    supportsAta: false,
    supportsNvme: false,
    supportsSed: false,
  },
  {
    id: "dev-ssd-sata",
    path: "/dev/sdb",
    type: "SSD",
    model: "Samsung 870 EVO 1TB",
    serial: "SM870-44521",
    sizeBytes: "1000204886016",
    mounted: false,
    isSystemDisk: false,
    supportsAta: true,
    supportsNvme: false,
    supportsSed: false,
  },
  {
    id: "dev-ssd-nvme",
    path: "/dev/nvme0n1",
    type: "SSD",
    model: "WD Black SN850 500GB",
    serial: "WDBLK-77102",
    sizeBytes: "500107862016",
    mounted: true,
    isSystemDisk: true,
    supportsAta: false,
    supportsNvme: true,
    supportsSed: true,
  },
  {
    id: "dev-usb-1",
    path: "/dev/sdc1",
    type: "USB",
    model: "SanDisk Ultra 32GB",
    serial: "SD-88342",
    sizeBytes: "32000000000",
    mounted: false,
    isSystemDisk: false,
    supportsAta: false,
    supportsNvme: false,
    supportsSed: false,
  },
];

export const MOCK_PLANS: Record<string, SanitizationPlan> = {
  "dev-hdd-1": {
    method: "OVERWRITE_MULTI",
    nistCategory: "CLEAR",
    justification:
      "On HDDs, logical block addresses map directly to physical locations, so overwrite-based sanitization reliably destroys data at the addressed location.",
    limitations: null,
  },
  "dev-ssd-sata": {
    method: "ATA_SECURE_ERASE",
    nistCategory: "PURGE",
    justification:
      "ATA Secure Erase is a firmware-level command executed by the drive controller itself, bypassing the wear-leveling mismatch that makes logical overwrite unreliable on SSDs.",
    limitations: null,
  },
  "dev-ssd-nvme": {
    method: "CRYPTO_ERASE",
    nistCategory: "PURGE",
    justification:
      "This drive supports self-encryption. Destroying the encryption key renders all data cryptographically inaccessible instantly, without relying on physical overwrite.",
    limitations: null,
  },
  "dev-usb-1": {
    method: "OVERWRITE_SINGLE",
    nistCategory: "CLEAR",
    justification: "Software overwrite applied at the logical level.",
    limitations:
      "USB flash controllers use wear-leveling that software cannot fully inspect. Overwrite does not guarantee physical cell erasure — for high-assurance disposal, physical destruction is recommended.",
  },
};

export const MOCK_JOBS: Job[] = [
  {
    id: "job-1001",
    type: "ERASE",
    status: "COMPLETED",
    progress: 100,
    deviceId: "dev-hdd-1",
    device: MOCK_DEVICES[0],
    eraseMethod: "OVERWRITE_MULTI",
    approvalStatus: "APPROVED",
    verified: true,
    residualRiskScore: 0.02,
    residualRiskLevel: "LOW",
    errorMessage: null,
    certificate: { id: "cert-9001" } as Certificate,
    createdAt: "2026-09-04T09:12:00Z",
  },
  {
    id: "job-1002",
    type: "RECOVER",
    status: "RUNNING",
    progress: 62,
    deviceId: "dev-usb-1",
    device: MOCK_DEVICES[3],
    eraseMethod: null,
    verified: null,
    residualRiskScore: null,
    residualRiskLevel: null,
    errorMessage: null,
    createdAt: "2026-09-05T10:41:00Z",
  },
  {
    id: "job-1003",
    type: "ERASE",
    status: "QUEUED",
    progress: 0,
    deviceId: "dev-ssd-sata",
    device: MOCK_DEVICES[1],
    eraseMethod: "ATA_SECURE_ERASE",
    approvalStatus: "PENDING",
    verified: null,
    residualRiskScore: null,
    residualRiskLevel: null,
    errorMessage: null,
    createdAt: "2026-09-05T11:02:00Z",
  },
  {
    id: "job-1004",
    type: "ERASE",
    status: "FAILED",
    progress: 40,
    deviceId: "dev-ssd-nvme",
    device: MOCK_DEVICES[2],
    eraseMethod: "CRYPTO_ERASE",
    approvalStatus: "APPROVED",
    verified: false,
    residualRiskScore: null,
    residualRiskLevel: null,
    errorMessage: "Device disconnected mid-operation. No partial key destruction occurred.",
    createdAt: "2026-09-03T15:20:00Z",
  },
];

export const MOCK_CERTIFICATES: Certificate[] = [
  {
    id: "cert-9001",
    jobId: "job-1001",
    method: "OVERWRITE_MULTI",
    standard: "NIST_800_88",
    verificationResult: true,
    contentHash: "8f3a2e1c9b7d4f60a1e2c3b4d5e6f7081920a1b2c3d4e5f60718293a4b5c6d7e",
    prevCertHash: null,
    signature: "3045022100c1a2...9f8e",
    pdfPath: "/certificates/cert-9001.pdf",
    createdAt: "2026-09-04T09:14:00Z",
  },
];

export const MOCK_AUDIT: AuditEvent[] = [
  {
    id: "ae-1",
    jobId: "job-1001",
    actorName: "operator1",
    eventType: "ERASE_REQUESTED",
    payload: JSON.stringify({ deviceId: "dev-hdd-1", scope: "whole_drive" }),
    eventHash: "a1b2c3",
    prevEventHash: null,
    timestamp: "2026-09-04T09:10:00Z",
  },
  {
    id: "ae-2",
    jobId: "job-1001",
    actorName: "admin",
    eventType: "ERASE_APPROVED",
    payload: JSON.stringify({ jobId: "job-1001" }),
    eventHash: "b2c3d4",
    prevEventHash: "a1b2c3",
    timestamp: "2026-09-04T09:11:00Z",
  },
  {
    id: "ae-3",
    jobId: "job-1001",
    actorName: "operator1",
    eventType: "ERASE_COMPLETED",
    payload: JSON.stringify({ verified: true, riskLevel: "LOW" }),
    eventHash: "c3d4e5",
    prevEventHash: "b2c3d4",
    timestamp: "2026-09-04T09:14:00Z",
  },
];

export const MOCK_RECOVERED_FILES: RecoveredFile[] = [
  {
    id: "rf-1",
    jobId: "job-1002",
    fileName: "IMG_2049.JPG",
    fileType: "jpg",
    offsetStart: "1048576",
    offsetEnd: "3245728",
    isFragmented: false,
    isTruncated: false,
    reconstructionMethod: "contiguous",
    fragmentCount: 1,
    confidenceScore: 0.95,
    confidenceLevel: "HIGH",
    headerScore: 1,
    structureScore: 0.95,
    parserScore: 0.98,
    fragmentationScore: 1,
    reasons: ["Valid JPEG header and footer", "Image decoded successfully (1920×1080)"],
    storedPath: "/recovered/rf-1.jpg",
  },
  {
    id: "rf-2",
    jobId: "job-1002",
    fileName: "invoice_march.pdf",
    fileType: "pdf",
    offsetStart: "9291008",
    offsetEnd: "9532416",
    isFragmented: true,
    isTruncated: false,
    reconstructionMethod: "two_segment_heuristic",
    fragmentCount: 2,
    confidenceScore: 0.71,
    confidenceLevel: "MEDIUM",
    headerScore: 1,
    structureScore: 0.6,
    parserScore: 0.65,
    fragmentationScore: 0.55,
    reasons: [
      "Valid PDF header found",
      "Reconstructed from 2 segments using proximity heuristic",
      "Parser reported minor object table irregularity",
    ],
    storedPath: "/recovered/rf-2.pdf",
  },
  {
    id: "rf-3",
    jobId: "job-1002",
    fileName: null,
    fileType: "jpg",
    offsetStart: "18209024",
    offsetEnd: "18344960",
    isFragmented: false,
    isTruncated: true,
    reconstructionMethod: null,
    fragmentCount: 1,
    confidenceScore: 0.32,
    confidenceLevel: "LOW",
    headerScore: 1,
    structureScore: 0.1,
    parserScore: 0,
    fragmentationScore: 0.2,
    reasons: ["Header signature matched only", "Footer missing — file likely truncated"],
    storedPath: "/recovered/rf-3.jpg",
  },
];

export const DEMO_MODE = true;
